# TensorFlow básico

In [3]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

In [2]:
# Certifique-se de usar 1.3 para correspondência de sintaxe exata!
print(tf.__version__)

2.3.0


## Tensors

In [3]:
hello = tf.constant('Hello')

In [4]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [5]:
world = tf.constant('World')

In [6]:
result = hello + world

In [7]:
result

<tf.Tensor 'add:0' shape=() dtype=string>

In [8]:
type(result)

tensorflow.python.framework.ops.Tensor

In [9]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [10]:
result

b'HelloWorld'

** Computações **

In [11]:
tensor_1 = tf.constant(1)
tensor_2 = tf.constant(2)

In [12]:
type(tensor_1)

tensorflow.python.framework.ops.Tensor

In [13]:
tensor_1 + tensor_2

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [14]:
sess

In [15]:
sess.close()

## Operações

In [16]:
const = tf.constant(10)

In [17]:
fill_mat = tf.fill((4,4),10)

In [18]:
myzeros = tf.zeros((4,4))

In [19]:
myones = tf.ones((4,4))

In [20]:
myrandn = tf.random_normal((4,4),mean=0,stddev=0.5)

In [21]:
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)

In [22]:
my_ops = [const,fill_mat,myzeros,myones,myrandn,myrandu]

## Sessão Interativa

Útil para sessões de notebook

In [23]:
# Execute esta célula apenas uma vez!
sess = tf.InteractiveSession()

In [24]:
for op in my_ops:
    print(op.eval())
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[ 0.1459299  -0.09848005 -0.0375897   0.0421433 ]
 [ 0.06855951  0.76334196 -0.22668882  0.41304633]
 [-0.13082723  0.26586267 -0.41742074  0.57086086]
 [-0.9670953  -0.10714459  0.44161856  0.2923559 ]]


[[0.07520676 0.572122   0.16827428 0.87046885]
 [0.4763975  0.77081907 0.7129787  0.6638013 ]
 [0.5961863  0.49019063 0.22042263 0.83118486]
 [0.90010965 0.12575471 0.5951922  0.37282526]]




## Multiplicação de matrizes

In [25]:
a = tf.constant([ [1,2],
                  [3,4] ])

In [26]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [27]:
b = tf.constant([[10],[100]])

In [28]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [29]:
result = tf.matmul(a,b)

In [30]:
result.eval()

array([[210],
       [430]])